# This is required for Continuous Integration for Autoware using the simulator
# and remote update (Over The Air update) to real cars.
# If you have any additional questions, please contact us at #tier4-dev channel.

version: 2

artifacts:
  - name: main
    build:
      type: tier4/universe/main/amd64/v1

simulations:
  - name: planning_sim_v2
    type: planning_sim_v2
    scenario_parameter_group: common # Necessary to define the name for each vehicle type
    simulator:
      deployment:
        type: container
        artifact: main
      runtime:
        type: standard1/amd64/medium
      parameters:
        vehicle_model: lexus
        sensor_model: aip_xx1
        autoware_launch_package: autoware_launch
        autoware_launch_file: planning_simulator.launch.xml
        architecture_type: awf/universe/20230906
        initialize_duration: "90"

  - name: obstacle_detection
    type: obstacle_detection
    simulator:
      deployment:
        type: container
        artifact: main
      runtime:
        type: standard1/amd64/medium

  - name: ndt_convergence
    type: ndt_convergence
    simulator:
      deployment:
        type: container
        artifact: main
      runtime:
        type: standard1/amd64/large

  - name: localization
    type: localization
    simulator:
      deployment:
        type: container
        artifact: main
      runtime:
        type: standard1/amd64/large

  - name: obstacle_segmentation
    type: obstacle_segmentation
    simulator:
      deployment:
        type: container
        artifact: main
      runtime:
        type: standard1/amd64/medium

  - name: performance_diag
    type: performance_diag
    simulator:
      deployment:
        type: container
        artifact: main
      runtime:
        type: standard1/amd64/medium

  - name: perception
    type: perception
    simulator:
      deployment:
        type: container
        artifact: main
      runtime:
        type: standard1/amd64/medium

release:
  components:
    - name: autoware
      deployment:
        type: rootfs
        artifact: main

scenario_parameter_groups:
  # Necessary to update the parameters for each vehicle type
  - name: common
    parameters:
      __ego_center_x__: 1.345
      __ego_center_y__: 0
      __ego_center_z__: 1.25
      __ego_dimensions_width__: 1.896
      __ego_dimensions_length__: 4.89
      __ego_dimensions_height__: 2.5
      wheel_radius: 0.383
      wheel_width: 0.235
      wheel_base: 2.79 # between front wheel center and rear wheel center
      wheel_tread: 1.64 # between left wheel center and right wheel center
      front_overhang: 1.0 # between front wheel center and vehicle front
      rear_overhang: 1.1 # between rear wheel center and vehicle rear
      left_overhang: 0.128 # between left wheel center and vehicle left
      right_overhang: 0.128 # between right wheel center and vehicle right
      max_steer_angle: 0.70 # [rad]
      obstacle_stop_line_distance: 5.0
      crosswalk_stop_line_distance: 3.5
      walkway_stop_line_distance: 3.5
      intersection_stop_line_distance: 3.0
      traffic_light_stop_line_distance: 0.0
